"""add WA info to submissions

Revision ID: 1a02f5c5e0b3
Revises: f40eea688c3e
Create Date: 2026-03-14 15:56:00.967706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a02f5c5e0b3'
down_revision: Union[str, Sequence[str], None] = 'f40eea688c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('wrong_tc_id', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('wrong_output', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'testcases', ['wrong_tc_id'], ['id'])
    op.drop_column('submissions', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'wrong_output')
    op.drop_column('submissions', 'wrong_tc_id')
    # ### end Alembic commands ###
