"""remove testcase, add data_path

Revision ID: 36ab550900d4
Revises: a4623564bbba
Create Date: 2026-03-17 14:54:10.160713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ab550900d4'
down_revision: Union[str, Sequence[str], None] = 'a4623564bbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('submissions_wrong_tc_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_index(op.f('ix_testcases_id'), table_name='testcases')
    op.drop_table('testcases')
    op.add_column('problems', sa.Column('data_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'data_path')
    op.create_table('testcases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tc_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('testcases_problem_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('testcases_pkey'))
    )
    op.create_index(op.f('ix_testcases_id'), 'testcases', ['id'], unique=False)
    op.create_foreign_key(op.f('submissions_wrong_tc_id_fkey'), 'submissions', 'testcases', ['wrong_tc_id'], ['id'])
    # ### end Alembic commands ###
