"""add time_used and memory_used to submissions

Revision ID: a4623564bbba
Revises: b788d6630847
Create Date: 2026-03-16 15:13:34.110894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4623564bbba'
down_revision: Union[str, Sequence[str], None] = 'b788d6630847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('time_used', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('memory_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'memory_used')
    op.drop_column('submissions', 'time_used')
    # ### end Alembic commands ###
