"""add multi-language support

Revision ID: b788d6630847
Revises: 1a02f5c5e0b3
Create Date: 2026-03-15 16:04:01.293247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b788d6630847'
down_revision: Union[str, Sequence[str], None] = '1a02f5c5e0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'time_limit')
    op.add_column('submissions', sa.Column('language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'language')
    op.add_column('problems', sa.Column('time_limit', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
